export enum AppRoutes {
  MAIN = "main",
  ACTOR_DETAILS = "actor_details",
  MOVIE_DETAILS = "movie_details",
  POPULAR_FILMS = "popular_films",
  TOP_250 = "top_250",
  VAMPIRE = "vampire",
  COMICS = "comics",
  FAMILY = "family",
  ROMANTIC = "romantic",
  ZOMBIE = "zombie",
  CATASTROPHE = "catastrophe",
  POPULAR_SERIALS = "poppular_serials",
  FILMS = "films",
  SERIALS = "serials",
  CARTOONS = "cartoons",
}

export const RoutePath: Record<AppRoutes, string> = {
  [AppRoutes.MAIN]: "/",
  [AppRoutes.ACTOR_DETAILS]: "/actor/:id",
  [AppRoutes.MOVIE_DETAILS]: "/movie/:id",
  [AppRoutes.POPULAR_FILMS]: "/collections/TOP_POPULAR_MOVIES",
  [AppRoutes.TOP_250]: "/collections/TOP_250_MOVIES",
  [AppRoutes.VAMPIRE]: "/collections/VAMPIRE_THEME",
  [AppRoutes.COMICS]: "/collections/COMICS_THEME",
  [AppRoutes.FAMILY]: "/collections/FAMILY",
  [AppRoutes.ROMANTIC]: "/collections/LOVE_THEME",
  [AppRoutes.ZOMBIE]: "/collections/ZOMBIE_THEME",
  [AppRoutes.CATASTROPHE]: "/collections/CATASTROPHE_THEME",
  [AppRoutes.POPULAR_SERIALS]: "/collections/POPULAR_SERIES",
  [AppRoutes.FILMS]: "/FILM",
  [AppRoutes.SERIALS]: "/TV_SERIES",
  [AppRoutes.CARTOONS]: "/CARTOONS",
};
