import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./styles/index.css";
import { ThemeProvider } from "./providers/ThemeProvider";
import { classNames } from "@/shared/lib/classNames/classNames";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={classNames("", {}, [poppins.variable])}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
