import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { classNames } from "@/shared/lib/classNames/classNames";
import "./styles/index.css";
import { Header } from "@/widgets/Header";
import { ThemeProvider } from "./providers/ThemeProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={classNames("", {}, [poppins.variable])}>
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
