import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { classNames } from "@/shared/lib/classNames/classNames";
import "./styles/index.css";
import { Header } from "@/widgets/Header";
import { ThemeProvider } from "./providers/ThemeProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const messages = await getMessages();
  const locale = await getLocale();
  return (
    <html lang="en">
      <body className={classNames("", {}, [poppins.variable])}>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
